export enum Color {
    Primary = "primary",
    Secondary = "secondary",
    Success = "success",
    Danger = "danger",
    Warning = "warning",
    Info = "info",
    Light = "light",
    Dark = "dark",
    Link = "link",
    Blue = "primary",
    Grey = "secondary",
    Gray = "secondary",
    Green = "success",
    Red = "danger",
    Yellow = "warning",
    Teal = "info",
    White = "light",
    Black = "dark"
}
